# This file contains the commands for creating PizzaCodebase folders
# The folder structure and commands were generated by ChatGPT 3.5
# The folders have already been created in the exercise, so there is no
# need for you to execute this file.

mkdir PizzaCodebase
mkdir PizzaCodebase/Cheese
mkdir PizzaCodebase/Cheese/Mozzarella
mkdir PizzaCodebase/Cheese/Mozzarella/Shredded
mkdir PizzaCodebase/Cheese/Mozzarella/Sliced
mkdir PizzaCodebase/Cheese/Cheddar
mkdir PizzaCodebase/Cheese/Cheddar/Mild
mkdir PizzaCodebase/Cheese/Cheddar/Sharp
mkdir PizzaCodebase/Toppings
mkdir PizzaCodebase/Toppings/Meat
mkdir PizzaCodebase/Toppings/Meat/Pepperoni
mkdir PizzaCodebase/Toppings/Meat/Sausage
mkdir PizzaCodebase/Toppings/Meat/Bacon
mkdir PizzaCodebase/Toppings/Vegetables
mkdir PizzaCodebase/Toppings/Vegetables/Mushrooms
mkdir PizzaCodebase/Toppings/Vegetables/BellPeppers
mkdir PizzaCodebase/Toppings/Vegetables/Onions
mkdir PizzaCodebase/Toppings/Extras
mkdir PizzaCodebase/Toppings/Extras/Pineapple
mkdir PizzaCodebase/Toppings/Extras/Olives
mkdir PizzaCodebase/Crusts
mkdir PizzaCodebase/Crusts/Thin
mkdir PizzaCodebase/Crusts/Thin/WholeWheat
mkdir PizzaCodebase/Crusts/Thin/GlutenFree
mkdir PizzaCodebase/Crusts/Thick
mkdir PizzaCodebase/Crusts/Thick/Stuffed
mkdir PizzaCodebase/Crusts/Thick/DeepDish
mkdir PizzaCodebase/Sauce
mkdir PizzaCodebase/Sauce/Marinara
mkdir PizzaCodebase/Sauce/Alfredo
mkdir PizzaCodebase/Sauce/BBQ
